# Generated by Django 6.0.3 on 2026-03-29 07:01

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_remove_room_description_remove_room_thumbnail_url'),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='RoomEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Embedding',
            },
        ),
    ]
