# Generated by Django 6.0.3 on 2026-03-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.PositiveIntegerField()),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Đang hiệu lực'), ('ended', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='rooms.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Chủ hộ'), ('member', 'Thành viên ở cùng')], default='member', max_length=20)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
