# Generated by Django 5.1 on 2026-03-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_lease_created_at_lease_updated_at_room_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('success', 'Thành công'), ('danger', 'Quan trọng')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available / Trống'), ('booked', 'Booked / Đã đặt chỗ'), ('occupied', 'Occupied / Đã cho thuê'), ('maintenance', 'Maintenance / Bảo trì')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(help_text='Tên khách gọi điện', max_length=100)),
                ('tenant_phone', models.CharField(help_text='Số điện thoại khách', max_length=15)),
                ('expected_move_in_date', models.DateField(help_text='Ngày dự kiến dọn vào')),
                ('deposit_amount', models.PositiveIntegerField(default=0, help_text='Số tiền cọc giữ chỗ')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận cọc'), ('cancelled', 'Đã hủy'), ('completed', 'Đã nhận phòng')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Ghi chú thêm (ví dụ: khách đòi sơn lại tường)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='backend.room')),
            ],
        ),
    ]
