# Generated by Django 6.0.3 on 2026-03-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('electricity', 'Điện'), ('water', 'Nước')], max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Đơn giá / kWh hoặc / m³', max_digits=10)),
                ('effective_date', models.DateField(help_text='Ngày bắt đầu áp dụng đơn giá này')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('electricity', 'Điện'), ('water', 'Nước')], max_length=20)),
                ('billing_month', models.DateField(help_text='Tháng tính (chọn ngày 1 của tháng)')),
                ('previous_reading', models.DecimalField(decimal_places=2, help_text='Chỉ số cũ', max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, help_text='Chỉ số mới', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Đơn giá tại thời điểm ghi', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='rooms.room')),
            ],
            options={
                'ordering': ['-billing_month'],
                'unique_together': {('room', 'utility_type', 'billing_month')},
            },
        ),
    ]
